- messaging/coap/engine.c
> Fix blockwise response timeout

- api/oc_rep.c
Possible null pointer dereference
fix for:
https://github.com/iotivity/iotivity-lite/issues/5
> fix for issue #5: possible null pointer dereference

- api/cloud/oc_cloud_manager.c
when refresh token failed we need to remove logged in status
because we need to refresh the token and make login again.
+ proper set error code for connection error
> cloud: don't publish resources when refresh token failed

- .github/workflows/doxygen.yml
Automatically builds and deploys doxygen to the iotivity-lite-doxygen github pages repo.
> Automatic building and deployment of doxygen.

- .github/workflows/doxygen-publish.yml
- include/oc_client_state.h
- include/oc_core_res.h
> more doxygen

- apps/simpleserver.c
Simple server should implement Random PIN.  This PR implements that.
> Add random PIN functionality to simpleserver

- python/obt_gui/README.md
- python/obt_gui/ui.py
- python/oc_python.c
> addition of readme.

- messaging/coap/observe.c
When generating the representation for the /oic/d
resource the getter checks the endpoint_t version
provided as argument to the call. If the endpoint
is NULL or has an old version the piid field
is skipped.
When sending observation messages NULL was used
as the endpoint value, therefore the piid field
was never present in the notifications.
The issue is fixed by taking the endpoint value
from the currently handled observer.
> Fix issue oic/d piid issue with notification (#40)

- api/cloud/oc_cloud_store.c
https://openconnectivity.org/specs/OCF_Device_To_Cloud_Services_Specification_v2.2.5.pdf
Table: 13
Fixes #195
> cloud: fix cis initialization

- include/oc_enums.h
- security/oc_obt.c
> enum doxygen update

- include/oc_cred.h
- security/oc_cred.c
- security/oc_cred_internal.h
Make oc_sec_get_creds, oc_sec_get_cred_by_credid and oc_sec_remove_cred_by_credid functions public.
> Add functions to public API

- python/iotivity.py
- python/obt_gui/ui.py
- python/oc_python.c
- python/oc_python.h
Added automated mediator for OCF-MQTT proxy (And minor improvements to the python obt)
> Obt python mqtt

- api/oc_core_res.c
- api/oc_swupdate.c
Reverts iotivity/iotivity-lite#229
> Revert "Update swupdate resource"

- port/android/oc_config.h
- port/arduino/adapter/oc_config.h
- port/esp32/adapter/include/oc_config.h
- port/linux/oc_config.h
- port/openthread/oc_config.h
- port/windows/oc_config.h
- port/zephyr/src/oc_config.h
- security/oc_pstat.c
Turned device name wiping to default ON
> Fix for Issue #247

- messaging/coap/observe.c
https://www.rfc-editor.org/rfc/rfc7641.html#section-4.2
Depends on fix: https://github.com/plgd-dev/hub/pull/767
> send cancellation notification when resource has been deleted

- api/cloud/oc_cloud.c
- api/cloud/oc_cloud_manager.c
- api/cloud/oc_cloud_resource.c
Update required state and payload condition for the update to go through.
> cloud: update configuration resource handling

- api/cloud/oc_cloud.c
- api/cloud/oc_cloud_context.c
- api/cloud/oc_cloud_internal.h
- api/cloud/oc_cloud_manager.c
- api/oc_server_api.c
- include/oc_api.h
- include/oc_cloud.h
- security/oc_doxm.c
Enable Setting of next ping Delay and timeout through oc_cloud_set_keepalive callback Function.
> cloud: configure keepalive

- api/cloud/oc_cloud.c
- api/oc_ri.c
- include/oc_client_state.h
- include/oc_ri.h
- messaging/coap/transactions.c
- messaging/coap/transactions.h
- security/oc_tls.c
- swig/swig_interfaces/oc_api.i
when connection has been closed by peer or client.
> client: return OC_CONNECTION_CLOSED to client handler

- api/oc_ri.c
- api/unittest/ocapitest.cpp
- security/oc_certs.c
- security/oc_certs_internal.h
- security/unittest/certstest.cpp
> when connection was closed, remove associated timeout callbacks

- api/oc_blockwise.c
- api/oc_helpers.c
- api/oc_mnt.c
- api/oc_resource_factory.c
- apps/client_block_linux.c
- apps/server_block_linux.c
- include/oc_blockwise.h
- messaging/coap/observe.c
- messaging/coap/oc_coap.h
- security/oc_cred.c
- security/oc_doxm.c
- security/unittest/tls_cert_test.cpp
Do not include internal headers from public headers.
> Fix public includes

- api/oc_ri.c
> oc_delayed_delete_resource fix segfault

- .github/workflows/ctt-bot.yml
- .github/workflows/plgd-device-test-with-cfg.yml
- .github/workflows/pr-format.yml
docker/build-push-action v3 -> v4
peter-evans/create-or-update-comment v1 -> v3
> Update GitHub actions

- .github/workflows/android.yml
- api/cloud/unittest/cloud_manager_test.cpp
- api/oc_collection.c
- api/oc_core_res.c
- api/oc_discovery.c
- api/oc_endpoint.c
- api/oc_swupdate.c
- api/plgd/plgd_time.c
- apps/cloud_certification_tests.c
- messaging/coap/observe.c
- port/android/Makefile
- port/android/ifaddrs-android.c
- port/esp32/adapter/src/ipadapter.c
- port/linux/Makefile
- port/windows/ipadapter.c
- security/oc_doxm.c
- security/oc_obt.c
- security/oc_sdi.c
- security/unittest/oscore_test.cpp
- swig/java_lang/oc_iotivity_lite_jni.c
- swig/java_lang/oc_iotivity_lite_jni.h
- swig/swig_interfaces/oc_api.i
- swig/swig_interfaces/oc_collection.i
- swig/swig_interfaces/oc_rep.i
- swig/swig_interfaces/oc_uuid.i
- tests/gtest/Device.cpp
- util/oc_compiler.h
Fix compilation on older GCC / clang versions that don't support the fallthrough attribute.
> Update compilator attributes

- api/cloud/oc_cloud_rd.c
- api/oc_core_res.c
- api/oc_mnt.c
- api/oc_mnt_internal.h
- api/unittest/maintenancetest.cpp
- api/unittest/platformtest.cpp
Fix issues reported by SonarCloud and add tests.
> api: refactor mnt resource
