iotivity/iotivity-lite

api/cloud/oc_cloud_manager.c
While retrying to connect to the cloud, keep last error to `CLOUD_OK`
This should fix #35 
@jkralik @WAvdBeek @ondrejtomcik
=> Fix: While retrying to connect to the cloud, keep last error to CLOUD_OK

api/cloud/oc_cloud.c, api/oc_server_api.c, api/oc_server_api_internal.h, include/oc_api.h
Do not invoke oc_cloud_delete_resource directly
in oc_server_api.c, because not all targets link
with oc_cloud source code. Instead assign
oc_cloud_delete_resource to global pointer if
cloud is enabled and invoke this pointer (if set).
=> api: fix oc_delayed_delete_resource function

api/cloud/oc_cloud.c
It could happen, that after a `OC_RESET` the cloud store does not reset the values for `cps` (i.e. the reset value for `cps` is only in memory). That can cause the cloud manager to enter a wrong state, when the iotivity-lite server is restarted.
This PR fixes the issue.
Pleaes review: @jkralik
=> Persist cloud store after cps and last_error were reset.

api/cloud/oc_cloud.c, api/cloud/oc_cloud_apis.c, api/cloud/oc_cloud_rd.c, api/cloud/rd_client.c, api/cloud/rd_client.h, api/cloud/unittest/rd_client_test.cpp, include/oc_cloud.h
Instead of hardcoded Time to Live value of
86400 seconds (=1 day) for published resources,
add configurable member to oc_cloud_context_t.
By default the ttl value is now set to 0 in
initializer, but can be modified by a setter
to the desired value.
=> api/cloud: make Time to Live configurable

api/cloud/oc_cloud.c, api/cloud/oc_cloud_internal.h, api/cloud/oc_cloud_rd.c, include/oc_cloud.h
If resouce links Time to Live is unlimited then republishing
published resource links each hour is not necessary.
=> api/cloud: don't schedule unnecessary republishing of links

port/linux/ipadapter.c, port/linux/tcpadapter.c
system always peak free port and when SO_REUSEADDR is set, then multiple
process of device with small chance system can peak same port.
eg for 1000 process it is cca 20ports - replicated via docker.
=> linux: don't set SO_REUSEADDR for random port

messaging/coap/engine.c
UDP packets can be duplicated by a router, switch, docker...
So if you run over 1000 devices at docker and duplication of packet
occurs during the blockwise transfer, then BWT is terminated by sending
a reset message. eg you find 999 devices over discovery.
So to avoid such an issue we drop duplicated messages for BWT.
=> fix: deduplicate message for blockwise

api/cloud/oc_cloud_apis.c, api/cloud/oc_cloud_internal.h
Some older cloud implementations expect the deregister
requests to have access token in the query otherwise
they regard the request as invalid. To support such
implementations we append the token to query if
the overall size of the request header is shorter
or equal to COAP_MAX_HEADER_SIZE.
=> api/cloud: include short tokens in deregister query

api/oc_main.c, api/oc_main.h, apps/cloud_server.c, messaging/coap/engine.c
When factory reset occurs, the device waits(2s) for closing TLS
connections. And during these 2s someone starts owning the device
again, he fails because the device closes all connections including
owning connection. For that, we drop all commands which come for
that time.
FYI: @ondrejtomcik, @Danielius1922
=> fix: during the wait for closing TLS connection, drop commands

port/oc_log.h
- reduce length of  
DEBUG ==> D
WARNING ==> W
ERROR ==> E
and reduce the __FILE__ to print only the filename without path
=> improve logging (reducing output)

api/oc_ri.c
=> Workaround to avoid infinite loop when no query parms are present in a

apps/simpleserver.c
The Linux-based simple switch implements the oic.d.light type but does not implement the mandatory oic.r.switch.binary resource.  This syncs the Linux version with the windows version.
=> Add binary switch resource

messaging/coap/separate.c
In order to ensure CSRs work on embedded devices, /oic/sec/csr had been
configured to respond using separate responses (empty ACK followed by
payload in a separate message.) However, these separate responses still
contained the CoAP Observe header, even though the resource is not
capable of handling Observe requests, which is in violation of RFC7641
section 4.1.
This commit ensures that the Observe header is not added to separate
response messages.
=> fix failure in CT1.2.21

api/cloud/oc_cloud_manager.c, api/oc_ri.c, apps/simpleserver.c
We can't remove the currently processed delayed callback because when
the callback returns OC_EVENT_DONE, a double release occurs. So we set up
the flag to remove it, and when it's over, we've removed it.
```
[root@image]# cat asan.txt
=================================================================
==24==ERROR: AddressSanitizer: attempting double-free on 0x606000b87d80 in thread T0:
#0 0x7fc5e8121277 in __interceptor_free (/usr/lib/libasan.so.5+0x107277)
#1 0x7fc5e7ebfa03 in _oc_memb_free ./iotivity-lite/util/oc_memb.c:159
#2 0x7fc5e7ed3f7f in poll_event_callback_timers ./iotivity-lite/api/oc_ri.c:464
#3 0x7fc5e7ed4027 in check_event_callbacks ./iotivity-lite/api/oc_ri.c:486
#4 0x7fc5e7ed67c0 in process_thread_timed_callback_events ./iotivity-lite/api/oc_ri.c:1617
#5 0x7fc5e7ebff15 in …
```
=> oc_event_callback: fix double free memory

messaging/coap/observe.c
When the client is observing a resource via BWT, then the client
cancel it, observation destroys cancelation response which is not
expected by
https://datatracker.ietf.org/doc/html/rfc7641#section-3.6 .
=> fix cancel observation via BWT

api/cloud/oc_cloud.c, api/cloud/oc_cloud_internal.h, api/cloud/oc_cloud_rd.c, include/oc_cloud.h, swig/swig_interfaces/oc_cloud.i
After successful refresh token call, login call is automatically
invoked. And succesful login in turn always invokes republishing
of already published resources to cloud. This is unnecessary,
the only thing that happened was that the access token had its
lifetime extended and this doesn't warant the republishing
of resources.
=> cloud: don't republish resources after refresh

api/oc_rep.c
Copy the size of the struct and not the size of the pointer to struct
=> api: fix memcpy argument in oc_rep_encoder_create_map

api/oc_rep.c
@JonasAnderssonn this was the simplest solution to your problem, but it's a bit fragile. If anybody adds a similar log you'll have the same problem again (how did you manage to sneak a custom `OC_WRN` past the compiler anyway? I guess you're compiling on a platform without `-Werror`).
@jkralik maybe we could add a new macro - `OC_LOG_CUSTOM` or something like that and when it is defined then in oc_log.h no `OC_LOG*` macros are defined and the implementer must provide definitions in a prefix header.
=> Fix compilation with custom OC_WRN definition

api/oc_rep.c, api/unittest/reptest.cpp, include/oc_rep.h
Add missing functions to encode a OC_REP_NIL value type to CborNullType.
=> Add function to encode CborNullType value

CMakeLists.txt
Cloud functionality requires client and server components. That causes linker errors with the server-only library when the library is built with `OC_CLOUD_ENABLED=ON`.
I missed to test that specific configuration in the previous PR https://github.com/iotivity/iotivity-lite/pull/181.
=> Fix: Remove cloud from server-only library in CMake build

security/oc_tls.c, security/oc_tls.h
Expose add function to allow clients to add custom peers to endpoints.
Add documentation to public peer functions.
=> TLS: add oc_tls_add_peer to public API

deps/mbedtls.cmake
Add compilation definitions with OC_DEBUG to mbedtls to avoid linker error when debugging logs are enabled.
=> CMake: fix build of mbedtls when debug logs are enabled

.github/workflows/cmake-windows.yml
Virtual environment windows-latest now defaults to windows-2022. Update workflows to work with this new environment.
=> Update github workflow for Windows

api/cloud/oc_cloud.c, api/cloud/oc_cloud_apis.c, api/cloud/oc_cloud_internal.h, api/cloud/oc_cloud_manager.c, api/cloud/oc_cloud_store.c
I noticed that during the initialization of the cloud manager it tries to register to a cloud ([cloud_register](https://github.com/iotivity/iotivity-lite/blob/master/api/cloud/oc_cloud_manager.c#L295) is called), even though there is no cloud configuration stored.
Eventually this leads to the `cps` property of the `/CoapCloudConfResURI` to change to `OC_CPS_FAILED`.
@jkralik proposed to initialize the `cis` property with NULL (instead of "coaps+tcp://127.0.0.1") to fix the issue, but that wasn't enough. I noticed that now `cloud_store_initialize` is basically a duplicate of `cloud_store_deinit`, so I removed `cloud_store_deinit` along the way.
To fix the issue, I added a check `ctx->store.cps == OC_CPS_READYTOREGISTER` in `cloud_start_process` to prevent the call of `cloud_register` …
=> Fix cloud registration during initialization

security/oc_cred.c, security/oc_csr.c, security/oc_tls.c
- possible override stack in CSR
- enforce PSK length according [specification](https://openconnectivity.org/specs/OCF_Security_Specification_v2.2.5.pdf) - 13.3.3.1 Symmetric key formatting
=> fixing csr buffer and enforce psk length during add

include/oc_cred.h, security/oc_cred.c
Add oc_sec_parse_cred function to add credentials
to device by parsing them from a payload retrieved
from some endpoint.
=> Add public function to parse credentials

include/oc_acl.h, security/oc_acl.c, security/oc_acl_internal.h, security/oc_store.c
Add oc_sec_apply_acl function to add ACLs to device by parsing them from a payload retrieved from some endpoint.
=> Add public function to parse ACLs

include/oc_acl.h, include/oc_cred.h, security/oc_acl.c, security/oc_cred.c
Remove dumpToStorage parameters from oc_sec_apply_acl and
oc_sec_apply_cred function. The dump to storage functions
\- oc_sec_dump_acl and oc_sec_dump_cred \- are public and
thus can be invoked directly by the caller.
=> security: simplify public API

api/oc_core_res.c, api/oc_swupdate.c
I would like to propose some changes to the implementation of the software update resource:
- Update the `nv` property in `oc_swupdate_notify_new_version_available`
- Clear the `nv` property in `oc_swupdate_notify_done`
- Perform follow-up action only on success in `oc_swupdate_notify_*` functions, i.e. check the result from the registered implementation before performing the follow-up action automatically.
- Remove the string length restriction for `purl`: IMO 63 characters is too low.
- Allow setting the `purl` property without the need to provide `swupdateaction` and `updatetime` in request: Setting the `purl` is not a timed action, more a configuration step.
- As the software update resource is a DCR, the URL should be prefixed with `oic/` as other DCR. And IMO `swu` is a better name …
=> Update swupdate resource

.github/workflows/static-analysis.yml, CMakeLists.txt, security/oc_cred.c, security/oc_pki.c, security/oc_tls.c, security/oc_tls.h, security/unittest/tls_cert_test.cpp, security/unittest/tlstest.cpp
Add test to verify consistency of internal lists containing
identity certificates.
=> security: fix removing trust anchors

api/oc_core_res.c, api/oc_swupdate.c
Reverting commit [Allow setting purl without swupdateaction and updatetime in request](https://github.com/iotivity/iotivity-lite/pull/229/commits/c2221514895e46b478ada3fbb1bdad52b67c20d3) from #229 should fix the failing CTT tests.
@SiMet: Can you confirm this this PR fixes the CTT tests?
=> Fix CTT tests for swupdate resource

api/oc_discovery.c, api/oc_server_api_internal.h, apps/cloud_certification_tests.c, messaging/coap/observe.c
An empty representation should be sent to the observer for a resource when it is deleted.
=> fix /oic/res batch observation - deleting resource

include/oc_swupdate.h
Table 18 of the OCF Core Optional specification v2.2.5 for the `oic.r.softwareupdate` resource lists the codes of the "swupdateresult" property. It contains a code for "Unsupported protocol for download URL" (7), which is missing in the `enum oc_swupdate_result_t`.
=> Add missing oc_swupdate_result_t value

api/oc_swupdate.c
According to the specification the `swupdateaction` value `upgrade` should be accepted by the `oic.r.softwareupdate` resource for a POST request, but is declined due to a comparison bug.
=> Fix validation of swupdateaction to allow upgrade action

api/cloud/oc_cloud.c
Do not destroy the list of published resources, but move the
resources into the to-be-published list when oc_cloud_manager_stop
is invoked.
=> cloud: reset lists of published resources on stop

api/oc_client_api.c, api/oc_rep.c, messaging/coap/coap.c, port/esp32/adapter/src/tcpadapter.c, port/linux/tcpadapter.c, port/oc_assert.h, python/oc_python.c, security/oc_tls.c, util/oc_memb.c
Addressed issues:
- clang-analyzer-deadcode.DeadStores
- clang-analyzer-valist.Uninitialized
- clang-analyzer-core.CallAndMessage
=> Fix issues reported by clang-tidy

.github/workflows/build.yml, port/esp32/README.md
To be able to apply iotivity-lite patches to mbedTLS in the ESP32 components we must checkout a commit in the repository where ESP32 uses mbedTLS v3.1.0
=> Fix ESP32 Github job

api/unittest/coreresourcetest.cpp, api/unittest/ocapitest.cpp, include/oc_acl.h, include/oc_cred.h, port/unittest/clocktest.cpp, port/unittest/storagetest.cpp, security/oc_acl.c, security/oc_acl_internal.h, security/oc_cred.c, security/oc_cred_internal.h, security/unittest/acltest.cpp, security/unittest/oscore_hkdf_test.cpp, security/unittest/oscore_test.cpp, security/unittest/tls_cert_test.cpp, security/unittest/tlstest.cpp, tests/itc/ri/src/RIGeneralIntegrationTest.cpp
Add public function to clear Access Control Entries (ACE) matching a filter from given device.
=> security/acl: add oc_sec_acl_clear API function

port/linux/tcpsession.c, port/oc_connectivity_internal.h, port/unittest/connectivitytest.cpp
On internal errors during TCP connect retry immediately instead of waiting for full retry interval. Only timeout should wait for the full interval to pass.
=> linux: update asynchrounous TCP connect

api/cloud/oc_cloud.c, include/oc_cloud.h
If the cloud configuration resource is updated with non-empty data then manager should be always started or restarted.
=> cloud: start manager after configuration update

.github/workflows/sonar-cloud-analysis.yml, api/cloud/oc_cloud_apis.c, api/cloud/unittest/cloud_access_test.cpp, api/cloud/unittest/rd_client_test.cpp, security/oc_tls.c, security/oc_tls.h, security/unittest/tls_peer_test.cpp, security/unittest/tlstest.cpp
Function removes all TLS peers that are matched by the filtering function.
=> tls: add oc_tls_peer_clear public function

deps/mbedtls.cmake
Since the iotivity-lite headers include mbedtls headers, the mbedtls library needs to be installed also when it is statically linked. The CMake property EXCLUDE_FROM_ALL prevented that.
=> Install mbedtls also when used as static library

patches/01-ocf-x509san-anon-psk.patch, security/oc_audit.c, security/oc_oscore_engine.c, security/oc_tls.c
Use mbedtls_ssl_export_keys_t to get master secret, server and client random bytes. Previously it was obtained by accessing internal structures.
=> TLS: use public API to get mbedTLS data

.github/workflows/docker-build-publish.yml
When building several images, some of them fail with 'io: read/write on closed pipe' error and cause the whole job to fail.
The issue is in build-push-action:
https://github.com/docker/build-push-action/issues/761
=> Fix error when publishing docker images to Ghcr

api/cloud/oc_cloud.c, api/cloud/oc_cloud_apis.c, api/cloud/oc_cloud_context.c, api/cloud/oc_cloud_context_internal.h, api/cloud/oc_cloud_internal.h, api/cloud/oc_cloud_manager.c, api/cloud/oc_cloud_manager_internal.h, api/cloud/oc_cloud_resource.c, api/cloud/oc_cloud_store.c, api/cloud/oc_cloud_store_internal.h, api/cloud/unittest/cloud_manager_test.cpp, api/cloud/unittest/cloud_store_test.cpp, api/cloud/unittest/cloud_test.cpp, api/oc_rep.c, api/oc_rep_internal.h, api/oc_ri.c, api/oc_ri_internal.h, api/unittest/ocapitest.cpp, include/oc_api.h, include/oc_cloud.h, include/oc_ri.h, port/esp32/main/CMakeLists.txt, security/oc_pstat.c
Instead of OC_STATUS_SERVICE_UNAVAILABLE use OC_REQUEST_TIMEOUT when oc_do_get_with_timeout, oc_do_post_with_timeout, ... end in a timeout. There are other scenarios that end OC_STATUS_SERVICE_UNAVAILABLE and it was not possible to determine that a timeout occurred. With a new status code OC_REQUEST_TIMEOUT it is always determinable.
=> api: use code OC_REQUEST_TIMEOUT for timeouts

CMakeLists.txt, api/oc_ri.c, messaging/coap/coap.c, messaging/coap/coap.h, messaging/coap/coap_internal.h, messaging/coap/engine.c, messaging/coap/separate.c, port/unittest/connectivitytest.cpp, security/oc_pstat.c, util/oc_process.c
- remove the global variable from public header
- provide internal setter and getters
- fix issue when the status remained in CLOSE_ALL_TLS_SESSIONS state in some scenarios
=> Fix global coap status value

port/linux/dns.c
=> linux: call freeaddrinfo only when getaddrinfo returns 0

port/linux/ipadapter.c, port/linux/tcpadapter.c, port/linux/tcpsession.c
The signal handler was empty if OC_HAS_FEATURE_TCP_ASYNC_CONNECT was not defined. This most likely in leaking of TCP sessions should have been freed.
Additional logs were added to enable better log debugging.
=> linux: always handle signal in TCP

.github/workflows/ghcr-cleanup.yml
- always keep the image with the tag 'master'
- in the scheduled clean-up job delete only images that are at least one month old
=> Update GitHub clean-up action

api/oc_network_events.c, api/oc_tcp.c, api/oc_tcp_internal.h, api/oc_udp.c, api/oc_udp_internal.h, api/unittest/tcptest.cpp, api/unittest/udptest.cpp, messaging/coap/coap.c, messaging/coap/coap.h, messaging/coap/engine.c, messaging/coap/oscore.c, messaging/coap/unittest/coapsignaltest.cpp, port/android/tcpadapter.c, port/esp32/adapter/src/tcpadapter.c, port/esp32/main/CMakeLists.txt, port/linux/tcpsession.c, port/windows/tcpadapter.c, port/windows/vs2015/IoTivity-lite.vcxproj, port/windows/vs2015/IoTivity-lite.vcxproj.filters, port/zephyr/src/Makefile, security/oc_oscore_engine.c, security/unittest/oscore_test.cpp
The network thread will now perform a validation check on incoming data via TCP/UDP. Any data that fails the validation check will result in the termination of the connection for TCP or dropping message for UDP.
Fixes #417
=> validate incoming data in network thread

.github/workflows/plgd-hub-tests.yml, apps/cloud_server.c, include/oc_pki.h, port/oc_log_internal.h, security/oc_certs.c, security/oc_certs_internal.h, security/oc_csr.c, security/oc_keypair.c, security/oc_keypair_internal.h, security/oc_obt.c, security/oc_obt_certs.c, security/oc_pki.c, security/oc_pki_internal.h, security/oc_pstat.c, security/oc_store.c, security/oc_tls.c, security/unittest/csrtest.cpp, security/unittest/keypairtest.cpp, security/unittest/obt_certstest.cpp, security/unittest/pkitest.cpp, tests/gtest/KeyPair.cpp
To integrate TPM with iotivity-lite, the mbedtls library is used for cryptography. There are four main functions that need to be implemented:
1. **Generate public and private key**: The `mbedtls_pk_ecp_gen_key` function generates a private key for the CSR of the identity certificate when iotivity-lite doesn't have a private key in the keypair storage. In this function, a private key needs to be generated in the TPM, and the public key `mbedtls_pk_context` needs to be filled.
2. **Free private key in TPM**: The `pk_free_key` function frees the private key in the TPM. This function is called when a factory reset is performed or when the keypair storage does not match the TPM during the generation of the CSR with the reference key.
3. **Store reference key to credential resource**: The …
=> PKI/TPM: allow to set pk functions for TPM use

.github/workflows/docker-build-publish.yml
Switch to pep440 versioning scheme in the helper Github action docker/metadata-action@v4. It seems that the IoTivity versioning format "X.Y.Z.R" (where "X.Y.Z" is the OCF Specification Version and "R" is the version of the C library) is no longer recognized by the action as matching the format of semantic versioning.
=> Fix versioning scheme in the Publish docker images job

api/oc_ri.c, api/plgd/plgd_time.c, api/unittest/plgdtimetest.cpp
Only OC_CONNECTION_CLOSED closes the session and invokes the session handler. Timeout status code just invoke and remove the client cb, the session is kept intact.
=> plgd-time: fix closing of session on fetch

api/cloud/oc_cloud_resource.c, api/oc_collection.c, api/oc_core_res.c, api/oc_discovery.c, api/oc_introspection.c, api/oc_mnt.c, api/oc_push.c, api/oc_ri.c, api/oc_server_api.c, api/oc_server_api_internal.h, api/oc_swupdate.c, api/plgd/plgd_time.c, api/unittest/resourcetest.cpp, apps/cloud_server.c, include/oc_api.h, include/oc_ri.h, messaging/coap/engine.c, messaging/coap/observe.c, security/oc_acl.c, security/oc_ael.c, security/oc_cred.c, security/oc_csr.c, security/oc_doxm.c, security/oc_pstat.c, security/oc_sdi.c, security/oc_sp.c
In cases of errors, iotivity-lite fails to populate the body. With the implementation of this callback function, you can customize and populate/replace the body as per your requirements.
=> provides API to set callback for oc_send_response

api/client/oc_client_cb.c, api/oc_event_callback.c, api/oc_event_callback_internal.h, api/oc_ri.c, api/oc_ri_internal.h, api/unittest/RIServerTest.cpp, api/unittest/eventcallbacktest.cpp, include/oc_core_res.h, messaging/coap/engine.c, messaging/coap/observe.c, messaging/coap/observe.h, messaging/coap/separate.c, messaging/coap/separate.h, port/esp32/main/CMakeLists.txt
- move to standalone file
- fix SonarCloud issues
- add tests
=> api: refactor event callbacks

api/oc_swupdate.c, api/oc_swupdate_internal.h, api/unittest/swupdatetest.cpp, include/oc_swupdate.h, tests/gtest/Storage.cpp, tools/doxygen.ini, util/oc_list.h
This commit introduces the oc_swupdate_validate_update global function to the swupdate module. The function is responsible for validating Software Update payloads and triggering a callback function in case of any encountered errors.
=> swupdate: add API function for validating update payloads

api/oc_log.c, api/oc_log_internal.h, port/oc_log_internal.h
Updated the internal representation from an unsigned to a signed integer. The value OC_LOG_LEVEL_DISABLED (=-1) is now to disable logging during runtime. Whether a log level is enabled is checked by the '<' operator. Previously, when casting to uint8_t, the value overflowed to 255, causing all log levels to be enabled. This issue has been resolved by using a signed integer representation.
=> Fix runtime disabling of logging

port/android/storage.c, port/linux/storage.c, port/windows/storage.c, security/oc_tls.c, tests/gtest/tls/Service.cpp
Issues 319212 and 319248: bad check of error condition in SSL write
Issue 319221: overlapping memcpy when creating an incomming message
=> tls: Fix coverity issues

api/cloud/oc_cloud_resource.c, api/oc_helpers.c, api/oc_ri.c, include/oc_helpers.h, messaging/coap/coap.c, messaging/coap/engine.c, messaging/coap/observe.c, messaging/coap/oscore.c, messaging/coap/separate.c, messaging/coap/separate.h, messaging/coap/transactions.c, onboarding_tool/obtmain.c, port/android/storage.c, port/android/storage.h, port/arduino/adapter/storage.c, port/esp32/adapter/src/storage.c, port/linux/ipadapter.c, port/linux/storage.c, port/linux/storage.h, port/oc_storage_internal.h, port/unittest/storagetest.cpp, port/windows/storage.c, port/windows/storage.h, port/zephyr/src/storage.c, python/oc_python.c, python/oc_python.h, security/oc_cred.c, security/oc_obt.c, security/oc_oscore_context.c, security/oc_oscore_engine.c
Issue 321044: Out-of-bounds write
=> storage: fix coverity issues

security/oc_cred.c
Fix bug introduced by a62f7726500d5d1b0062ff4fd4f387fd5bcb132f
=> cred: set tag member when parsing a certificate to oc_sec_cred_t

CMakeLists.txt, messaging/coap/transactions.c, security/oc_pstat.c, security/oc_pstat_internal.h, util/oc_process.c, util/oc_process.h, util/unittest/processtest.cpp
This function allows the user to detect that reset has scheduled the closing of TLS sessions, but has not yet been executed.
This reverts removal of the function by commit 005c0756a4b09698e581f558ebd40541863e1db8
=> Return oc_process_is_closing_all_tls_sessions

port/linux/storage.c
This commit introduces error messages to provide more informative feedback for different scenarios during storage configuration and file operations.
=> linux: Add error messages for storage configuration and file operations

api/oc_etag.c, api/oc_storage.c, api/oc_swupdate.c, api/plgd/plgd_time.c, security/oc_store.c
In case resulting in the creation of a default configuration.
=> resource storages: generate a debug log instead of an error in case of a read failure

api/cloud/oc_cloud_apis.c, apps/cloud_server.c, security/oc_tls.c
Also, handle ownership transfer for the second device when the first device is already connected to the hub. Extend the cloud server to accommodate multiple servers and enhance the check for empty endpoints.
Fixes #531
=> Establish separate cloud connections for each device

api/oc_main.c, messaging/coap/engine.c
check if the iotivity-lite stack is initialized before processing new requests during shutdown.
```
#0  0x00007f5052dfa213 in ...
#1  0x00007f505306325f in ...
#2  0x00007f50527d1935 in oc_core_device_handler () from target:/lib/libiotivity-lite-client-server.so.2
#3  0x00007f50527e0fb1 in oc_ri_invoke_coap_entity_handler () from target:/lib/libiotivity-lite-client-server.so.2
#4  0x00007f50527eb799 in coap_receive () from target:/lib/libiotivity-lite-client-server.so.2
#5  0x00007f50527ec5b1 in process_thread_g_coap_engine () from target:/lib/libiotivity-lite-client-server.so.2
#6  0x00007f50527c8bb4 in call_process () from target:/lib/libiotivity-lite-client-server.so.2
#7  0x00007f50527c8f16 in do_event () from target:/lib/libiotivity-lite-client-server.so.2
#8  0x00007f50527c8f36 in …
```
=> Check iotivity-lite stack init before processing requests

api/oc_collection.c, api/oc_discovery.c, api/oc_endpoint.c, api/oc_endpoint_internal.h, api/oc_introspection.c, api/oc_push.c, api/unittest/eptest.cpp, api/unittest/plgdtimetest.cpp, include/oc_endpoint.h, include/oc_helpers.h, messaging/coap/observe.c, messaging/coap/transactions.c, port/common/oc_ip.c, port/common/oc_ip.h, port/linux/tcpsession.c, security/oc_tls.c, tests/gtest/Device.cpp, tests/gtest/Device.h, tests/gtest/Endpoint.cpp
=> use oc_endpoint_to_string64 to utilize stack

.github/workflows/cmake-linux.yml, CMakeLists.txt, api/oc_core_res.c, api/oc_discovery.c, api/oc_discovery_internal.h, api/oc_push.c, api/oc_query.c, api/oc_ri.c, api/unittest/querytest.cpp, apps/cloud_proxy.c, apps/server_certification_tests.c, apps/simpleserver-TVAppAndAction.c, apps/smart_home_server_linux.c, include/oc_api.h, include/oc_ri.h, messaging/coap/coap_options.h, security/oc_acl.c, security/oc_cred.c, security/oc_doxm.c, security/oc_roles.c, swig/swig_interfaces/oc_api.i, swig/swig_interfaces/oc_ri.i
Extend the function signature to include the include the length of the key. If the length of the key is known then a call to strlen can be avoided.
Added:
- oc_iterate_query_get_values_v1
- oc_get_query_value_v1
- oc_query_value_exists_v1
- oc_ri_get_query_value_v1
- oc_ri_query_exists_v1
Deprecated:
- oc_iterate_query_get_values
- oc_get_query_value
- oc_query_value_exists
- oc_ri_get_query_value
- oc_ri_query_exists
=> Update query public API

api/oc_base64.c, api/unittest/base64test.cpp, include/oc_base64.h
Extended the base64 to support encoding and decoding:
- using URL-safe characters
- with and without padding '=' at the end
=> Extend base64 module

port/linux/ipadapter.c, port/linux/oc_config.h, port/windows/ipadapter.c, port/windows/oc_config.h
IPv4 resource discovery uses a TTL (time-to-live) value of 1 (system default) for the multicast packets.
This prevents resources from being discovered when there are multiple routers in the local network where resources shall be discovered.
This PR allows to configure the TTL for IPv4 discovery at compile time with a new `OC_IPV4_MULTICAST_TTL` constant added to the `port/<platform>/oc_config.h` header. I have done it this way in order to not need to change the function signatures of the discovery functions.
=> Configure IPv4 multicast ttl for discovery

security/oc_tls.c
This commit handles the case where the connection is initialized by IoTivity-Lite (oc_tls_init_connection).
Example: Cloud Manager
=> Set interface index from incoming message if not set in TLS peer

api/cloud/oc_cloud.c
Upon loss of connection, the OC_CLOUD_LOGGED_IN bit is now removed. This implementation ensures that users receive a notification indicating the loss of connection.
=> Cloud: Trigger user callback upon cloud manager startup

api/cloud/oc_cloud.c, api/cloud/oc_cloud_apis.c, api/cloud/oc_cloud_context.c, api/cloud/oc_cloud_internal.h, api/cloud/oc_cloud_manager.c, api/cloud/oc_cloud_manager_internal.h, api/cloud/unittest/cloud_manager_test.cpp, api/cloud/unittest/cloud_test.cpp, include/oc_cloud.h
Enhance scheduling flexibility by enabling the setting of delay and timeout for actions, including jitter for added randomness.
=> Cloud: Add custom scheduler for improved cloud action handling

port/linux/ipadapter.c
In some cases, it can lead to issues because if the IP addresses are obtained through netlink and there is a failure due to ENOBUF, the device may report incorrect endpoints during the discovery process.
=> port/linux: Address Issues with ENOBUF Failure in Netlink IP Address Retrieval
